### ISSUE TITLE
Cannot install in Oxygen.2 ( cannot find xtext.xbase )

### ISSUE THREAD

**Issue by paulvi** [itemis/jbc#2]
When using marketplace drag-n-drop

<a href="http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=3579717" class="drag" title="Drag to your running Eclipse* workspace. *Requires Eclipse Marketplace Client"><img typeof="foaf:Image" class="img-responsive" src="https://marketplace.eclipse.org/sites/all/themes/solstice/public/images/marketplace/btn-install.png" alt="Drag to your running Eclipse* workspace. *Requires Eclipse Marketplace Client" /></a>

![image](https://user-images.githubusercontent.com/1614482/35328187-7bb5a634-0136-11e8-86ea-69d36dacf03f.png)

**Comment by paulvi** [comment]
Loot at https://marketplace.eclipse.org/content/jbc Errors tab, there are 34 such errors in the last 7 days

https://marketplace.eclipse.org/content/error/report/3881618

**Comment by kthoms** [comment]
The JBC feature will need a reference to the Xtext release update site
  http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
Oxygen does only contain Xtext 2.11

As a work around, configure the update site in Eclipse preferences _Install/Update / Available Software Sites_.

**Comment by paulvi** [comment]
Trying to install at home leads to worse result

![image](https://user-images.githubusercontent.com/1614482/35331919-0e10c1b4-0144-11e8-9a16-2493be54b0c7.png)

OK, that update site URL should be in README and on marketplace

**Comment by paulvi** [comment]
![image](https://user-images.githubusercontent.com/1614482/35366687-9c11264a-01b5-11e8-8607-604e88e0e2af.png)

**Comment by ArneDeutsch** [comment]
Starting with 1.2.1 there is now a composite update site containing all dependencies (including Xtext. This should resolve all update issues. Official update site will be updatesd soon.
